### ISSUE TITLE
No console

### ISSUE THREAD

**Issue by hugo4715** [Gogume1er/caoutchouc#1]
Hi,

When i run The caoutchouc jar file, using "java -jar Caoutchouc.jar --serverJar spigot.jar", it run the server without system.out redirected to the console (system.in is still redirected to the server and i can stop it fine)

Bye

**Comment by hugo4715** [comment]
Sample output: http://prnt.sc/dvwm8k

**Comment by Gogume1er** [comment]
Yep, we know this bug, but we don't have any idea why it appears (maybe log4j ?)
